# *#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
# Preprocessing Pipeline part 1  #
# *#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
#
# This script executes the complete preprocessing
# workflow for a single participant.
#
# Processing steps:
#   00) Bad channel detection + Maxwell filtering
#   01) PREP pipeline
#   02) Artifact annotation
#   03) ICA training
#
# Outputs generated by each step are saved and used
# by the next step independently.

# %%
# *#*#*#*#*#
# 1) Setup #
# *#*#*#*#*#
from pathlib import Path
from paths import create_output_folders
from step00_badch_maxwell import run_badch_maxwell
from step01_prep_pipeline import run_prep_pipeline
from step02_artifact_annotations import run_artifact_annotations
from step03_ica import run_train_ica


inroot_dir = Path(r"C:\Users\tomas\Desktop\COG_MEEG_EXP1_RELEASE")

# select subject
subject = "CB013"

sub_indir = Path(rf"C:\Users\tomas\Desktop\COG_MEEG_EXP1_RELEASE\{subject}")
sub_dur_indir = sub_indir / f"{subject}_EXP1_MEEG"

out_paths = create_output_folders(subject=subject, inroot=inroot_dir)

outroot_dir = r"C:\Users\tomas\Desktop\COG_MEEG_EXP1_RELEASE_OUTPUT"

# --- caminhos dos ficheiros ---
file_paths = [
    rf"{sub_dur_indir}\{subject}_MEEG_1_DurR1.fif",
    rf"{sub_dur_indir}\{subject}_MEEG_1_DurR2.fif",
    rf"{sub_dur_indir}\{subject}_MEEG_1_DurR3.fif",
    rf"{sub_dur_indir}\{subject}_MEEG_1_DurR4.fif",
    rf"{sub_dur_indir}\{subject}_MEEG_1_DurR5.fif",
]
names = ["dur1", "dur2", "dur3", "dur4", "dur5"]
dur_files = [sub_dur_indir / f"{subject}_MEEG_1_DurR{i}.fif" for i in range(1, 6)]
dur_files = [
    x for x in sub_dur_indir.glob("*") if x.suffix == ".fif" and "DurR" in x.name
]

# ficheiros de calibração e cross-talk
cal_file = rf"{sub_indir}\metadata\calibration_crosstalk_coreg\{subject}_ses-1_acq-calibration_meg.dat"
ct_file = rf"{sub_indir}\metadata\calibration_crosstalk_coreg\{subject}_ses-1_acq-crosstalk_meg.fif"


# *#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
# 2) Full preprocessing part 1  #
# *#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#


def run_full_pipeline_part1(subject):

    # *#*#*#*#*#*#*#
    # 2.1) Paths  #
    # *#*#*#*#*#*#*#
    # Define input/output directories and create
    # the preprocessing folder structure.
    # Locate all raw duration runs and create
    # standardized run names.

    inroot = Path(r"C:\Users\tomas\Desktop\COG_MEEG_EXP1_RELEASE")
    out_paths = create_output_folders(subject=subject, inroot=inroot)

    sub_indir = inroot / subject
    sub_dur_indir = sub_indir / f"{subject}_EXP1_MEEG"

    names = [f"dur{i}" for i in range(1, 6)]

    raw_files = sorted([x for x in sub_dur_indir.glob("*DurR*.fif")])

    # *#*#*#*#*#*#*#*#*#*#*#*#*#
    # 2.2) Maxwell filtering  #
    # *#*#*#*#*#*#*#*#*#*#*#*#*#
    # Detects bad channels, applies Signal Space
    # Separation (SSS), interpolate bad channels
    # and aligns runs to a common head position.

    raws_sss = run_badch_maxwell(
        file_paths=raw_files,
        cal_file=sub_indir
        / "metadata/calibration_crosstalk_coreg"
        / f"{subject}_ses-1_acq-calibration_meg.dat",
        ct_file=sub_indir
        / "metadata/calibration_crosstalk_coreg"
        / f"{subject}_ses-1_acq-crosstalk_meg.fif",
        out_paths=out_paths,
        subject=subject,
        names=names,
    )

    sss_files = [
        out_paths["00_badch_maxwell"] / f"{subject}_badch_maxwell_{n}.fif"
        for n in names
    ]

    # *#*#*#*#*#*#
    # 2.3) PREP  #
    # *#*#*#*#*#*#
    # Applies robust EEG preprocessing including
    # line-noise removal, referencing and bad
    # channel interpolation.

    raws_clean = run_prep_pipeline(
        file_paths=sss_files,
        out_paths=out_paths,
        subject=subject,
        names=names,
    )

    prep_files = [
        out_paths["01_prep_pipeline"] / f"{subject}_01_prep_pipeline_{n}.fif"
        for n in names
    ]

    # *#*#*#*#*#*#*#*#*#*#*#*##*#
    # 2.4) Artifact annotation #
    # *#*#*#*#*#*#*#*#*#*#*#*##*#
    # Automatically identifies segments containing
    # large artifacts and stores them as annotations
    # for later exclusion.

    raws_annotated = run_artifact_annotations(
        file_paths=prep_files,
        out_paths=out_paths,
        subject=subject,
        names=names,
    )

    annot_files = [
        out_paths["02_artifact_annotations"]
        / f"{subject}_02_artifact_annotations_{n}.fif"
        for n in names
    ]

    # *#*#*#*#*#*#*#*#*#
    # 2.6) ICA train  #
    # *#*#*#*#*#*#*#*#*#
    # Trains independent component decompositions
    # for MEG and EEG and identifies candidates for
    # physiological artifact components.

    ica_meg, ica_eeg = run_train_ica(
        file_paths=annot_files,
        out_paths=out_paths,
        subject=subject,
        names=names,
    )

    print(f"{subject} preprocessing part 1 completed.")


if __name__ == "__main__":
    run_full_pipeline_part1("CB013")


# %%
