# %%
# *#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
# Preprocessing Pipeline part 1  #
# *#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
#
# This script executes the complete preprocessing
# workflow for a single participant.
#
# Processing steps:
#   00) Bad channel detection + Maxwell filtering
#   01) PREP pipeline
#   02) Artifact annotation
#   03) ICA training
#
# Outputs generated by each step are saved and used
# by the next step independently.

# *#*#*#*#*#
# 1) Setup #
# *#*#*#*#*#
import mne
from blab_meeg.utils.paths import create_output_folders
from blab_meeg.preprocessing.step00_badch_maxwell import run_badch_maxwell
from blab_meeg.preprocessing.step01_prep_pipeline import run_prep_pipeline
from blab_meeg.preprocessing.step02_artifact_annotations import run_artifact_annotations
from blab_meeg.preprocessing.step03_ica import run_train_ica
from blab_meeg.utils.THE_DELETER import the_deleter
from blab_meeg.utils.load_inroot import load_inroot
from blab_meeg.utils.load_or_run_raws import (
    load_raws,
    load_or_run,
)
import time

# *#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
# 2) Full preprocessing part 1  #
# *#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#


def run_full_pipeline_part1(
    subject,
    run_maxwell=False,
    run_prep=True,
    run_artifact_annotation=True,
    run_ica=True,
    save_outputs=True,
    delete_intermediate_files=True,
):

    # *#*#*#*#*#*#*#
    # 2.1) Paths  #
    # *#*#*#*#*#*#*#
    # Define input/output directories and create
    # the preprocessing folder structure.
    # Locate all raw duration runs and create
    # standardized run names.

    start_time = time.perf_counter()

    # subjects that didn't pass the qc
    excluded_subjects = {
        "CA101",
        "CA108",
        "CB082",
    }

    if subject in excluded_subjects:
        print(f"{subject}: excluded by QC. Skipping.")
        return

    inroot_dir = load_inroot()

    # inroot_dir = Path("/home/blab/COGITATE/DATA/COG_MEEG_EXP1_RELEASE")

    # sub_indir = Path(rf"C:\Users\tomas\Desktop\COG_MEEG_EXP1_RELEASE\{subject}")
    sub_indir = inroot_dir / subject
    sub_dur_indir = sub_indir / f"{subject}_EXP1_MEEG"

    out_paths = create_output_folders(subject=subject, inroot=inroot_dir)

    raw_files = sorted(sub_dur_indir.glob("*DurR*.fif"))

    if len(raw_files) == 0:
        raise FileNotFoundError(f"No raw FIF files found for {subject}.")

    names = [f"dur{i + 1}" for i in range(len(raw_files))]

    raw_info = mne.io.read_raw_fif(raw_files[0], preload=False)
    has_eeg = len(mne.pick_types(raw_info.info, eeg=True)) > 0
    raw_info.close()

    print("\n" + "=" * 60)
    print(f"Subject: {subject}")
    print("=" * 60)
    print(f"Runs found: {len(raw_files)}")
    print(f"EEG available: {has_eeg}")

    # *#*#*#*#*#*#*#*#*#*#*#*#*#
    # 2.2) Maxwell filtering  #
    # *#*#*#*#*#*#*#*#*#*#*#*#*#
    # Detects bad channels, applies Signal Space
    # Separation (SSS), interpolate bad channels
    # and aligns runs to a common head position.

    raws_sss = load_or_run(
        run_step=run_maxwell,
        step_name="Maxwell filtering",
        runner=lambda: run_badch_maxwell(
            file_paths=raw_files,
            cal_file=sub_indir
            / "metadata/calibration_crosstalk_coreg"
            / f"{subject}_ses-1_acq-calibration_meg.dat",
            ct_file=sub_indir
            / "metadata/calibration_crosstalk_coreg"
            / f"{subject}_ses-1_acq-crosstalk_meg.fif",
            out_paths=out_paths,
            subject=subject,
            names=names,
            save_outputs=save_outputs,
        ),
        loader=lambda: load_raws(
            out_paths,
            "00_badch_maxwell",
            subject,
        ),
    )

    # *#*#*#*#*#*#
    # 2.3) PREP  #
    # *#*#*#*#*#*#
    # Applies robust EEG preprocessing including
    # line-noise removal, referencing and bad
    # channel interpolation.

    if has_eeg:
        raws_clean = load_or_run(
            run_step=run_prep,
            step_name="PREP",
            runner=lambda: run_prep_pipeline(
                raws_sss=raws_sss,
                out_paths=out_paths,
                subject=subject,
                names=names,
                save_outputs=save_outputs,
            ),
            loader=lambda: load_raws(
                out_paths,
                "01_prep_pipeline",
                subject,
            ),
        )

    else:
        print("No EEG detected. Skipping PREP.")
        raws_clean = raws_sss

    # *#*#*#*#*#*#*#*#*#*#*#*##*#
    # 2.4) Artifact annotation #
    # *#*#*#*#*#*#*#*#*#*#*#*##*#
    # Automatically identifies segments containing
    # large artifacts and stores them as annotations
    # for later exclusion.

    raws_annotated = load_or_run(
        run_step=run_artifact_annotation,
        step_name="Artifact annotation",
        runner=lambda: run_artifact_annotations(
            raws_clean=raws_clean,
            out_paths=out_paths,
            subject=subject,
            names=names,
            save_outputs=save_outputs,
        ),
        loader=lambda: load_raws(
            out_paths,
            "02_artifact_annotations",
            subject,
        ),
    )

    # *#*#*#*#*#*#*#*#*#
    # 2.6) ICA train  #
    # *#*#*#*#*#*#*#*#*#
    # Trains independent component decompositions
    # for MEG and EEG and identifies candidates for
    # physiological artifact components.

    if run_ica:
        print("\n===== Train ICA =====")

        run_train_ica(
            raws_annotated=raws_annotated,
            out_paths=out_paths,
            subject=subject,
            names=names,
            save_outputs=save_outputs,
            has_eeg=has_eeg,
        )

        print("✔ Train ICA complete.")

    if delete_intermediate_files:
        if has_eeg:
            the_deleter(
                out_paths,
                "00_badch_maxwell",
            )

            the_deleter(
                out_paths,
                "01_prep_pipeline",
            )

        else:
            the_deleter(
                out_paths,
                "00_badch_maxwell",
            )

    print(f"{subject} preprocessing part 1 completed.")
    elapsed = time.perf_counter() - start_time

    minutes = int(elapsed // 60)
    seconds = elapsed % 60

    print(f"\nFinished in {minutes} min {seconds:.1f} s")

    return


if __name__ == "__main__":
    run_full_pipeline_part1(
        subject="CA140",
    )

# %%
